"use client";

import { useState, useEffect } from "react";
import { createClient } from "../../supabase/client";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  FileText,
  Download,
  Eye,
  BarChart3,
  PieChart,
  Users,
} from "lucide-react";

interface Report {
  id: string;
  name: string;
  type: string;
  description: string;
  generated_at: string;
  generated_by: string;
  status: "generated" | "generating" | "failed";
  file_size?: string;
  parameters?: any;
}

interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  type: string;
  icon: React.ReactNode;
  fields: string[];
}

interface ReportGenerationProps {
  userRole: string;
}

// Utility function to sanitize user input
const sanitizeInput = (input: string): string => {
  if (!input) return "";
  return input
    .replace(/[\r\n]/g, " ")
    .replace(/[<>'"&]/g, (char) => {
      const entities: { [key: string]: string } = {
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#x27;",
        "&": "&amp;",
      };
      return entities[char] || char;
    })
    .trim();
};

// Enhanced content validation
const validateContent = (content: string, minLength: number = 100): boolean => {
  return Boolean(content && content.trim().length >= minLength);
};

// Generate real data content for reports
const generateReportContent = async (
  report: Report,
  supabase: any,
): Promise<string> => {
  const reportData = {
    name: sanitizeInput(report.name),
    type: report.type.replace("_", " ").toUpperCase(),
    generatedAt: new Date(report.generated_at).toLocaleDateString(),
    generatedBy: sanitizeInput(report.generated_by),
    description: sanitizeInput(report.description || ""),
  };

  let content = `REPORT: ${reportData.name}\n\n`;
  content += `Type: ${reportData.type}\n`;
  content += `Generated: ${reportData.generatedAt}\n`;
  content += `Generated By: ${reportData.generatedBy}\n`;
  content += `Description: ${reportData.description}\n\n`;

  try {
    if (report.type === "financial_summary") {
      const { data: funds } = await supabase.from("fund_sources").select("*");
      const { data: expenses } = await supabase
        .from("expenses")
        .select("*")
        .in("status", ["approved", "paid"]);

      const totalFunds =
        funds?.reduce((sum, f) => sum + (f.amount || 0), 0) || 0;
      const totalExpenses =
        expenses?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;
      const balance = totalFunds - totalExpenses;
      const utilizationRate =
        totalFunds > 0 ? ((totalExpenses / totalFunds) * 100).toFixed(1) : "0";

      content += `FINANCIAL SUMMARY REPORT\n========================\n\n`;
      content += `Total Funds Received: FRw ${totalFunds.toLocaleString()}\n`;
      content += `Total Expenses: FRw ${totalExpenses.toLocaleString()}\n`;
      content += `Remaining Balance: FRw ${balance.toLocaleString()}\n`;
      content += `Fund Utilization Rate: ${utilizationRate}%\n\n`;

      if (funds?.length) {
        content += `FUND SOURCES:\n`;
        funds.forEach((fund) => {
          content += `- ${fund.name}: FRw ${(fund.amount || 0).toLocaleString()} (${fund.is_restricted ? "Restricted" : "Unrestricted"})\n`;
        });
        content += `\n`;
      }
    } else if (report.type === "expense_report") {
      const { data: expenses } = await supabase
        .from("expenses")
        .select("*, budget_categories(name), projects(name)")
        .in("status", ["approved", "paid"]);

      const totalExpenses =
        expenses?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;
      const avgExpense = expenses?.length ? totalExpenses / expenses.length : 0;

      content += `EXPENSE ANALYSIS REPORT\n=======================\n\n`;
      content += `Total Expenses: FRw ${totalExpenses.toLocaleString()}\n`;
      content += `Number of Transactions: ${expenses?.length || 0}\n`;
      content += `Average Expense: FRw ${Math.round(avgExpense).toLocaleString()}\n\n`;

      if (expenses?.length) {
        content += `DETAILED EXPENSES:\n`;
        expenses.slice(0, 20).forEach((expense, i) => {
          const category = expense.budget_categories?.name || "Uncategorized";
          const project = expense.projects?.name || "General";
          content += `${i + 1}. ${expense.title} - FRw ${(expense.amount || 0).toLocaleString()} (${category}) - ${expense.expense_date} - ${expense.status}\n`;
        });
        content += `\n`;
      }
    } else if (report.type === "budget_variance") {
      const { data: categories } = await supabase
        .from("budget_categories")
        .select("*, expenses(amount, status)");

      content += `BUDGET VARIANCE REPORT\n======================\n\n`;

      if (categories?.length) {
        let totalBudget = 0;
        let totalActual = 0;

        content += `CATEGORY ANALYSIS:\n`;
        categories.forEach((category) => {
          const budgetAmount = category.budget_amount || 0;
          const actualExpenses =
            category.expenses
              ?.filter((e) => e.status === "approved" || e.status === "paid")
              ?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;

          const variance = budgetAmount - actualExpenses;
          const variancePercent =
            budgetAmount > 0
              ? ((variance / budgetAmount) * 100).toFixed(1)
              : "0";

          totalBudget += budgetAmount;
          totalActual += actualExpenses;

          content += `- ${category.name}:\n`;
          content += `  Budget: FRw ${budgetAmount.toLocaleString()}\n`;
          content += `  Actual: FRw ${actualExpenses.toLocaleString()}\n`;
          content += `  Variance: FRw ${variance.toLocaleString()} (${variancePercent}%)\n`;
          content += `  Status: ${variance >= 0 ? "Under Budget" : "Over Budget"}\n\n`;
        });

        const totalVariance = totalBudget - totalActual;
        const totalVariancePercent =
          totalBudget > 0
            ? ((totalVariance / totalBudget) * 100).toFixed(1)
            : "0";

        content += `OVERALL SUMMARY:\n`;
        content += `Total Budget: FRw ${totalBudget.toLocaleString()}\n`;
        content += `Total Actual: FRw ${totalActual.toLocaleString()}\n`;
        content += `Total Variance: FRw ${totalVariance.toLocaleString()} (${totalVariancePercent}%)\n`;
        content += `Budget Utilization: ${totalBudget > 0 ? ((totalActual / totalBudget) * 100).toFixed(1) : "0"}%\n\n`;
      }
    } else if (report.type === "donor_report") {
      const { data: fundSources } = await supabase
        .from("fund_sources")
        .select("*, donors(name, type)");

      const totalDonations =
        fundSources?.reduce((sum, f) => sum + (f.amount || 0), 0) || 0;
      const avgDonation = fundSources?.length
        ? totalDonations / fundSources.length
        : 0;

      content += `DONOR IMPACT REPORT\n===================\n\n`;
      content += `Total Donations: FRw ${totalDonations.toLocaleString()}\n`;
      content += `Number of Donors: ${fundSources?.length || 0}\n`;
      content += `Average Donation: FRw ${Math.round(avgDonation).toLocaleString()}\n\n`;

      if (fundSources?.length) {
        content += `DONOR CONTRIBUTIONS:\n`;
        fundSources.forEach((fund, i) => {
          const donorName = fund.donors?.name || "Anonymous";
          content += `${i + 1}. ${donorName} - FRw ${(fund.amount || 0).toLocaleString()} (${fund.name}) - ${fund.received_date}\n`;
        });
        content += `\n`;
      }
    }
  } catch (error) {
    content += `ERROR: Unable to fetch real data - ${error}\n\n`;
  }

  content += `REPORT METADATA\n===============\n`;
  content += `System: Pryro for NGO Financial Management\n`;
  content += `Export Time: ${new Date().toLocaleString()}\n`;
  content += `Data Source: Live Database\n\n`;

  return content;
};

// Calculate actual file size
const calculateFileSize = (content: string): string => {
  const bytes = new Blob([content]).size;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

export default function ReportGeneration({
  userRole = "admin",
}: ReportGenerationProps) {
  const [reports, setReports] = useState<Report[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [donors, setDonors] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const supabase = createClient();

  useEffect(() => {
    const initializeData = async () => {
      setLoading(true);
      await Promise.all([
        fetchReports(),
        fetchProjects(),
        fetchDonors(),
        fetchCategories(),
      ]);
      setLoading(false);
    };

    initializeData();
  }, []);

  const fetchReports = async () => {
    try {
      const { data, error } = await supabase
        .from("reports")
        .select("*")
        .order("generated_at", { ascending: false });

      if (!error && data) {
        const formattedReports = data.map((report) => ({
          id: report.id,
          name: sanitizeInput(report.name),
          type: report.type,
          description: sanitizeInput(
            report.description || `Generated report: ${report.name}`,
          ),
          generated_by: sanitizeInput(report.generated_by || "Unknown User"),
          generated_at: report.generated_at,
          status: report.status || "generated",
          parameters: report.parameters || {},
          file_size: "~1.2 MB",
        }));
        setReports(formattedReports);
      }
    } catch (error) {
      console.error("Error fetching reports:", error);
      setReports([]);
    }
  };

  const fetchProjects = async () => {
    try {
      const { data, error } = await supabase
        .from("projects")
        .select("id, name")
        .order("name");

      if (!error && data) {
        setProjects(data.map((p) => ({ ...p, name: sanitizeInput(p.name) })));
      } else {
        setProjects([
          { id: "1", name: "Education Program" },
          { id: "2", name: "Healthcare Initiative" },
          { id: "3", name: "Community Development" },
        ]);
      }
    } catch (error) {
      setProjects([
        { id: "1", name: "Education Program" },
        { id: "2", name: "Healthcare Initiative" },
        { id: "3", name: "Community Development" },
      ]);
    }
  };

  const fetchDonors = async () => {
    try {
      const { data, error } = await supabase
        .from("donors")
        .select("id, name")
        .order("name");

      if (!error && data) {
        setDonors(data.map((d) => ({ ...d, name: sanitizeInput(d.name) })));
      } else {
        setDonors([
          { id: "1", name: "Individual Donors" },
          { id: "2", name: "Corporate Partners" },
          { id: "3", name: "Foundation Grants" },
        ]);
      }
    } catch (error) {
      setDonors([
        { id: "1", name: "Individual Donors" },
        { id: "2", name: "Corporate Partners" },
        { id: "3", name: "Foundation Grants" },
      ]);
    }
  };

  const fetchCategories = async () => {
    try {
      const { data, error } = await supabase
        .from("budget_categories")
        .select("id, name")
        .order("name");

      if (!error && data) {
        setCategories(data.map((c) => ({ ...c, name: sanitizeInput(c.name) })));
      } else {
        setCategories([
          { id: "1", name: "Program Expenses" },
          { id: "2", name: "Administrative Costs" },
          { id: "3", name: "Personnel" },
          { id: "4", name: "Equipment & Supplies" },
        ]);
      }
    } catch (error) {
      setCategories([
        { id: "1", name: "Program Expenses" },
        { id: "2", name: "Administrative Costs" },
        { id: "3", name: "Personnel" },
        { id: "4", name: "Equipment & Supplies" },
      ]);
    }
  };

  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<string>("");
  const [reportParameters, setReportParameters] = useState({
    name: "",
    dateFrom: "",
    dateTo: "",
    projects: [] as string[],
    donors: [] as string[],
    categories: [] as string[],
    includeCharts: true,
    includeDetails: true,
    format: "pdf",
  });

  const reportTemplates: ReportTemplate[] = [
    {
      id: "financial_summary",
      name: "Financial Summary Report",
      description:
        "Comprehensive overview of income, expenses, and fund balances",
      type: "financial_summary",
      icon: <BarChart3 className="h-6 w-6" />,
      fields: ["dateRange", "projects", "includeCharts"],
    },
    {
      id: "budget_variance",
      name: "Budget Variance Report",
      description:
        "Compare actual expenses against budgeted amounts by category",
      type: "budget_variance",
      icon: <PieChart className="h-6 w-6" />,
      fields: ["dateRange", "categories", "projects", "includeCharts"],
    },
    {
      id: "donor_report",
      name: "Donor Impact Report",
      description:
        "Donor-focused report showcasing fund utilization and impact metrics",
      type: "donor_report",
      icon: <Users className="h-6 w-6" />,
      fields: [
        "dateRange",
        "donors",
        "projects",
        "includeDetails",
        "includeCharts",
      ],
    },
    {
      id: "expense_report",
      name: "Expense Analysis Report",
      description: "Detailed breakdown of expenses by category and project",
      type: "expense_report",
      icon: <PieChart className="h-6 w-6" />,
      fields: ["dateRange", "categories", "projects", "includeDetails"],
    },
  ];

  const handleGenerateReport = async () => {
    try {
      setGenerating(true);

      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) {
        alert("You must be logged in to generate reports.");
        return;
      }

      const sanitizedName = sanitizeInput(reportParameters.name);
      if (!sanitizedName.trim()) {
        alert("Please enter a report name.");
        return;
      }

      // Generate content to calculate actual file size
      const tempReport = {
        name: sanitizedName,
        type: selectedTemplate,
        description: `Generated report: ${sanitizedName}`,
        generated_by: user.email || "Unknown User",
        generated_at: new Date().toISOString(),
        parameters: reportParameters,
      };

      const content = await generateReportContent(
        tempReport as Report,
        supabase,
      );
      const actualFileSize = calculateFileSize(content);

      const newReport: Report = {
        id: Date.now().toString(),
        name: sanitizedName,
        type: selectedTemplate,
        description: `Generated report: ${sanitizedName}`,
        generated_by: user.email || "Unknown User",
        generated_at: new Date().toISOString(),
        status: "generated",
        parameters: reportParameters,
        file_size: actualFileSize,
      };

      setReports((prev) => [newReport, ...prev]);

      try {
        await supabase.from("reports").insert([
          {
            name: sanitizedName,
            type: selectedTemplate,
            description: `Generated report: ${sanitizedName}`,
            generated_by: user.id,
            status: "generated",
            parameters: reportParameters,
          },
        ]);
      } catch (dbError) {
        console.error("Database save failed:", dbError);
      }

      setShowGenerateDialog(false);
      setSelectedTemplate("");
      setReportParameters({
        name: "",
        dateFrom: "",
        dateTo: "",
        projects: [],
        donors: [],
        categories: [],
        includeCharts: true,
        includeDetails: true,
        format: "pdf",
      });

      alert(
        `Report "${sanitizedName}" generated successfully! Size: ${actualFileSize}`,
      );
      setTimeout(() => handleDownloadReport(newReport), 500);
    } catch (error) {
      console.error("Error generating report:", error);
      alert("An error occurred while generating the report. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadReport = async (report: Report) => {
    try {
      const format = report.parameters?.format || "pdf";

      if (format === "csv") {
        await downloadCSVReport(report);
      } else if (format === "excel") {
        await downloadExcelReport(report);
      } else {
        await downloadPDFReport(report);
      }
    } catch (error) {
      console.error("Download error:", error);
      alert("Error downloading report. Please try again.");
    }
  };

  const downloadPDFReport = async (report: Report) => {
    try {
      console.log("Starting PDF generation for:", report.name);

      // Generate real data content
      const reportContent = await generateReportContent(report, supabase);

      if (!validateContent(reportContent, 500)) {
        throw new Error("Generated content is insufficient for PDF creation");
      }

      console.log("Generated content length:", reportContent.length);

      // Create HTML content for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>${sanitizeInput(report.name)}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 40px;
              line-height: 1.6;
              color: #333;
            }
            .header {
              border-bottom: 3px solid #2563eb;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .title {
              font-size: 24px;
              font-weight: bold;
              color: #1e40af;
              margin-bottom: 10px;
            }
            .subtitle {
              font-size: 14px;
              color: #6b7280;
              margin-bottom: 5px;
            }
            .content {
              white-space: pre-line;
              font-size: 12px;
              line-height: 1.5;
            }
            .section {
              margin: 20px 0;
              padding: 15px;
              background-color: #f8fafc;
              border-left: 4px solid #2563eb;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              font-size: 10px;
              color: #6b7280;
              text-align: center;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">${sanitizeInput(report.name)}</div>
            <div class="subtitle">Generated: ${new Date(report.generated_at).toLocaleDateString()}</div>
            <div class="subtitle">Generated By: ${sanitizeInput(report.generated_by)}</div>
            <div class="subtitle">Report Type: ${report.type.replace("_", " ").toUpperCase()}</div>
          </div>
          
          <div class="section">
            <div class="content">${reportContent}</div>
          </div>
          
          <div class="footer">
            <p>Generated by Pryro for NGO Financial Management System</p>
            <p>Export Time: ${new Date().toLocaleString()}</p>
          </div>
        </body>
        </html>
      `;

      console.log("HTML content length:", htmlContent.length);

      // Validate HTML content
      if (!validateContent(htmlContent, 1000)) {
        throw new Error("HTML content is insufficient");
      }

      // Try to use jsPDF if available, otherwise fallback to HTML download
      try {
        const { jsPDF } = await import("jspdf");

        // Create PDF with proper configuration
        const pdf = new jsPDF({
          orientation: "portrait",
          unit: "mm",
          format: "a4",
        });

        // Set document properties
        pdf.setProperties({
          title: report.name,
          subject: `NGO Financial Report - ${report.type}`,
          author: report.generated_by,
          creator: "Pryro for NGO",
        });

        // Add content to PDF
        const lines = reportContent.split("\n");
        let yPosition = 20;
        const pageHeight = pdf.internal.pageSize.height;
        const margin = 20;

        // Add title
        pdf.setFontSize(16);
        pdf.setFont("helvetica", "bold");
        pdf.text(report.name, margin, yPosition);
        yPosition += 10;

        // Add metadata
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "normal");
        pdf.text(
          `Generated: ${new Date(report.generated_at).toLocaleDateString()}`,
          margin,
          yPosition,
        );
        yPosition += 5;
        pdf.text(`Generated By: ${report.generated_by}`, margin, yPosition);
        yPosition += 5;
        pdf.text(
          `Type: ${report.type.replace("_", " ").toUpperCase()}`,
          margin,
          yPosition,
        );
        yPosition += 15;

        // Add content
        pdf.setFontSize(9);
        lines.forEach((line) => {
          if (yPosition > pageHeight - margin) {
            pdf.addPage();
            yPosition = margin;
          }

          const wrappedLines = pdf.splitTextToSize(
            line || " ",
            pdf.internal.pageSize.width - 2 * margin,
          );
          pdf.text(wrappedLines, margin, yPosition);
          yPosition += wrappedLines.length * 4;
        });

        // Add footer to all pages
        const pageCount = pdf.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
          pdf.setPage(i);
          pdf.setFontSize(8);
          pdf.text(`Page ${i} of ${pageCount}`, margin, pageHeight - 10);
          pdf.text(
            `Generated: ${new Date().toLocaleString()}`,
            pdf.internal.pageSize.width - 60,
            pageHeight - 10,
          );
        }

        // Save PDF
        const fileName = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;
        pdf.save(fileName);

        console.log("PDF generated successfully");
        alert(`PDF report "${report.name}" downloaded successfully!`);
      } catch (pdfError) {
        console.error("jsPDF failed, using HTML fallback:", pdfError);

        // Fallback to HTML download
        const blob = new Blob([htmlContent], {
          type: "text/html;charset=utf-8",
        });

        if (blob.size === 0) {
          throw new Error("Failed to create HTML blob");
        }

        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);

        alert(
          `Report "${report.name}" downloaded as HTML. You can print this to PDF using your browser.`,
        );
      }
    } catch (error) {
      console.error("PDF generation error:", error);

      // Emergency fallback - create simple text file
      try {
        const emergencyContent = await generateReportContent(report, supabase);
        const blob = new Blob([emergencyContent], {
          type: "text/plain;charset=utf-8",
        });

        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);

        alert(
          `Report "${report.name}" downloaded as text file due to PDF generation error.`,
        );
      } catch (emergencyError) {
        console.error("Emergency fallback failed:", emergencyError);
        // Final fallback - simple text with basic info
        const basicContent = `Report: ${report.name}\nGenerated: ${new Date(report.generated_at).toLocaleDateString()}\nGenerated By: ${report.generated_by}\nType: ${report.type}\n\nNote: Unable to generate full report due to technical issues.`;
        const blob = new Blob([basicContent], {
          type: "text/plain;charset=utf-8",
        });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}_basic.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
        alert(
          "Basic report information downloaded. Please contact support for full report.",
        );
      }
    }
  };

  const downloadCSVReport = async (report: Report) => {
    try {
      console.log("Generating CSV report for:", report.name);

      const csvContent = [
        ["Report Name", "Type", "Generated Date", "Generated By"],
        [
          sanitizeInput(report.name),
          report.type.replace("_", " ").toUpperCase(),
          new Date(report.generated_at).toLocaleDateString(),
          sanitizeInput(report.generated_by),
        ],
        [],
        ["Report Data", "", "", ""],
      ];

      try {
        if (report.type === "financial_summary") {
          const { data: funds } = await supabase
            .from("fund_sources")
            .select("*");
          const { data: expenses } = await supabase
            .from("expenses")
            .select("*")
            .in("status", ["approved", "paid"]);

          const totalFunds =
            funds?.reduce((sum, f) => sum + (f.amount || 0), 0) || 0;
          const totalExpenses =
            expenses?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;

          csvContent.push(["Financial Overview", "Amount (FRw)", "Status"]);
          csvContent.push([
            "Total Funds",
            totalFunds.toLocaleString(),
            "Confirmed",
          ]);
          csvContent.push([
            "Total Expenses",
            totalExpenses.toLocaleString(),
            "Verified",
          ]);
          csvContent.push([
            "Balance",
            (totalFunds - totalExpenses).toLocaleString(),
            "Available",
          ]);

          if (funds?.length) {
            csvContent.push(
              [],
              ["Fund Sources", "Amount (FRw)", "Type", "Date"],
            );
            funds.forEach((fund) => {
              csvContent.push([
                fund.name,
                (fund.amount || 0).toLocaleString(),
                fund.is_restricted ? "Restricted" : "Unrestricted",
                fund.received_date || "N/A",
              ]);
            });
          }
        } else if (report.type === "expense_report") {
          const { data: expenses } = await supabase
            .from("expenses")
            .select("*, budget_categories(name)")
            .in("status", ["approved", "paid"]);

          if (expenses?.length) {
            csvContent.push([
              "Expense Item",
              "Amount (FRw)",
              "Category",
              "Date",
              "Status",
            ]);
            expenses.forEach((expense) => {
              csvContent.push([
                expense.title,
                (expense.amount || 0).toLocaleString(),
                expense.budget_categories?.name || "Uncategorized",
                expense.expense_date || "N/A",
                expense.status,
              ]);
            });
          }
        } else if (report.type === "budget_variance") {
          const { data: categories } = await supabase
            .from("budget_categories")
            .select("*, expenses(amount, status)");

          if (categories?.length) {
            csvContent.push([
              "Category",
              "Budget (FRw)",
              "Actual (FRw)",
              "Variance (FRw)",
              "Variance %",
              "Status",
            ]);
            categories.forEach((category) => {
              const budgetAmount = category.budget_amount || 0;
              const actualExpenses =
                category.expenses
                  ?.filter(
                    (e) => e.status === "approved" || e.status === "paid",
                  )
                  ?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;

              const variance = budgetAmount - actualExpenses;
              const variancePercent =
                budgetAmount > 0
                  ? ((variance / budgetAmount) * 100).toFixed(1)
                  : "0";

              csvContent.push([
                category.name,
                budgetAmount.toLocaleString(),
                actualExpenses.toLocaleString(),
                variance.toLocaleString(),
                `${variancePercent}%`,
                variance >= 0 ? "Under Budget" : "Over Budget",
              ]);
            });
          }
        } else if (report.type === "donor_report") {
          const { data: fundSources } = await supabase
            .from("fund_sources")
            .select("*, donors(name)");

          if (fundSources?.length) {
            csvContent.push(["Donor Name", "Amount (FRw)", "Fund", "Date"]);
            fundSources.forEach((fund) => {
              csvContent.push([
                fund.donors?.name || "Anonymous",
                (fund.amount || 0).toLocaleString(),
                fund.name,
                fund.received_date || "N/A",
              ]);
            });
          }
        }
      } catch (dataError) {
        csvContent.push([
          "Error",
          "Unable to fetch real data",
          dataError.message || "Unknown error",
        ]);
      }

      // Add footer
      csvContent.push(
        [],
        ["Report Footer", "", "", ""],
        ["Generated By", "Pryro for NGO System", "", ""],
        ["Export Time", new Date().toLocaleString(), "", ""],
        ["File Format", "CSV", "", ""],
      );

      // Convert to CSV string
      const csvString = csvContent
        .map((row) =>
          row
            .map((cell) => {
              const cellValue = (cell || "").toString();
              if (
                cellValue.includes(",") ||
                cellValue.includes('"') ||
                cellValue.includes("\n")
              ) {
                return `"${cellValue.replace(/"/g, '""')}"`;
              }
              return cellValue;
            })
            .join(","),
        )
        .join("\n");

      // Validate content
      if (!validateContent(csvString, 100)) {
        throw new Error("CSV content is insufficient");
      }

      // Create and download file
      const BOM = "\uFEFF"; // UTF-8 BOM for Excel compatibility
      const blob = new Blob([BOM + csvString], {
        type: "text/csv;charset=utf-8;",
      });

      if (blob.size === 0) {
        throw new Error("Failed to create CSV blob");
      }

      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);

      alert(`CSV report "${report.name}" downloaded successfully!`);
    } catch (error) {
      console.error("CSV generation error:", error);
      alert("Error generating CSV report. Please try again.");
    }
  };

  const downloadExcelReport = async (report: Report) => {
    try {
      console.log("Generating Excel report for:", report.name);

      let excelContent = `
        <html><head><meta charset="utf-8">
        <style>
          table { border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; font-weight: bold; }
          .header { background-color: #4472C4; color: white; font-weight: bold; }
        </style></head><body><table>
          <tr class="header"><td colspan="6"><b>${sanitizeInput(report.name)}</b></td></tr>
          <tr><td><b>Generated:</b></td><td>${new Date(report.generated_at).toLocaleDateString()}</td><td></td><td></td><td></td><td></td></tr>
          <tr><td><b>Generated By:</b></td><td>${sanitizeInput(report.generated_by)}</td><td></td><td></td><td></td><td></td></tr>
          <tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>
      `;

      try {
        if (report.type === "financial_summary") {
          const { data: funds } = await supabase
            .from("fund_sources")
            .select("*");
          const { data: expenses } = await supabase
            .from("expenses")
            .select("*")
            .in("status", ["approved", "paid"]);

          const totalFunds =
            funds?.reduce((sum, f) => sum + (f.amount || 0), 0) || 0;
          const totalExpenses =
            expenses?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;

          excelContent += `
            <tr class="header"><td colspan="6"><b>Financial Summary</b></td></tr>
            <tr><th>Item</th><th>Amount (FRw)</th><th>Status</th><th></th><th></th><th></th></tr>
            <tr><td>Total Funds</td><td>${totalFunds.toLocaleString()}</td><td>Confirmed</td><td></td><td></td><td></td></tr>
            <tr><td>Total Expenses</td><td>${totalExpenses.toLocaleString()}</td><td>Verified</td><td></td><td></td><td></td></tr>
            <tr><td>Balance</td><td>${(totalFunds - totalExpenses).toLocaleString()}</td><td>Available</td><td></td><td></td><td></td></tr>
          `;
        } else if (report.type === "budget_variance") {
          const { data: categories } = await supabase
            .from("budget_categories")
            .select("*, expenses(amount, status)");

          excelContent += `<tr class="header"><td colspan="6"><b>Budget Variance Analysis</b></td></tr>
            <tr><th>Category</th><th>Budget (FRw)</th><th>Actual (FRw)</th><th>Variance (FRw)</th><th>Variance %</th><th>Status</th></tr>`;

          categories?.forEach((category) => {
            const budgetAmount = category.budget_amount || 0;
            const actualExpenses =
              category.expenses
                ?.filter((e) => e.status === "approved" || e.status === "paid")
                ?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0;

            const variance = budgetAmount - actualExpenses;
            const variancePercent =
              budgetAmount > 0
                ? ((variance / budgetAmount) * 100).toFixed(1)
                : "0";

            excelContent += `<tr><td>${category.name}</td><td>${budgetAmount.toLocaleString()}</td>
              <td>${actualExpenses.toLocaleString()}</td><td>${variance.toLocaleString()}</td>
              <td>${variancePercent}%</td><td>${variance >= 0 ? "Under Budget" : "Over Budget"}</td></tr>`;
          });
        } else if (report.type === "expense_report") {
          const { data: expenses } = await supabase
            .from("expenses")
            .select("*, budget_categories(name)")
            .in("status", ["approved", "paid"]);

          excelContent += `<tr class="header"><td colspan="6"><b>Expense Analysis</b></td></tr>
            <tr><th>Item</th><th>Amount (FRw)</th><th>Category</th><th>Date</th><th>Status</th><th></th></tr>`;

          expenses?.slice(0, 20).forEach((expense) => {
            excelContent += `<tr><td>${expense.title}</td><td>${(expense.amount || 0).toLocaleString()}</td>
              <td>${expense.budget_categories?.name || "Uncategorized"}</td><td>${expense.expense_date || "N/A"}</td>
              <td>${expense.status}</td><td></td></tr>`;
          });
        }
      } catch (dataError) {
        excelContent += `<tr><td>Error</td><td>Unable to fetch real data</td><td>${dataError.message || "Unknown"}</td><td></td><td></td><td></td></tr>`;
      }

      excelContent += `
        </table>
        </body>
        </html>
      `;

      // Validate content
      if (!validateContent(excelContent, 500)) {
        throw new Error("Excel content is insufficient");
      }

      const blob = new Blob([excelContent], {
        type: "application/vnd.ms-excel;charset=utf-8;",
      });

      if (blob.size === 0) {
        throw new Error("Failed to create Excel blob");
      }

      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${sanitizeInput(report.name).replace(/[^a-zA-Z0-9]/g, "_")}.xls`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);

      alert(`Excel report "${report.name}" downloaded successfully!`);
    } catch (error) {
      console.error("Excel generation error:", error);
      alert("Error generating Excel report. Please try again.");
    }
  };

  const handlePreviewReport = async (report: Report) => {
    try {
      const reportContent = await generateReportContent(report, supabase);
      const previewContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${sanitizeInput(report.name)} - Preview</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
            .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .content { white-space: pre-line; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${sanitizeInput(report.name)}</h1>
            <p><strong>Generated:</strong> ${new Date(report.generated_at).toLocaleDateString()}</p>
            <p><strong>Generated By:</strong> ${sanitizeInput(report.generated_by)}</p>
            <p><strong>Type:</strong> ${report.type.replace("_", " ").toUpperCase()}</p>
          </div>
          <div class="content">${reportContent}</div>
        </body>
        </html>
      `;

      const previewWindow = window.open("", "_blank", "width=800,height=600");
      if (previewWindow) {
        previewWindow.document.write(previewContent);
        previewWindow.document.close();
      }
    } catch (error) {
      console.error("Preview error:", error);
      alert("Error opening report preview.");
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "generated":
        return "bg-green-100 text-green-800";
      case "generating":
        return "bg-yellow-100 text-yellow-800";
      case "failed":
        return "bg-red-100 text-red-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getTypeIcon = (type: string) => {
    const template = reportTemplates.find((t) => t.id === type);
    return template?.icon || <FileText className="h-4 w-4" />;
  };

  const selectedTemplateData = reportTemplates.find(
    (t) => t.id === selectedTemplate,
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64 bg-white">
        <div className="flex flex-col items-center gap-4">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
          <div className="text-gray-500">Loading report generation...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 bg-white">
      {/* Report Templates */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportTemplates.map((template) => (
          <Card
            key={template.id}
            className="hover:shadow-md transition-shadow cursor-pointer border-2 hover:border-blue-200"
          >
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                  {template.icon}
                </div>
                <div>
                  <CardTitle className="text-lg">{template.name}</CardTitle>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <CardDescription className="mb-4">
                {template.description}
              </CardDescription>
              <Dialog
                open={showGenerateDialog && selectedTemplate === template.id}
                onOpenChange={(open) => {
                  if (!open) {
                    setShowGenerateDialog(false);
                    setSelectedTemplate("");
                  }
                }}
              >
                <DialogTrigger asChild>
                  <Button
                    className="w-full"
                    onClick={() => {
                      setSelectedTemplate(template.id);
                      setShowGenerateDialog(true);
                    }}
                  >
                    Generate Report
                  </Button>
                </DialogTrigger>
              </Dialog>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Generate Report Dialog */}
      <Dialog open={showGenerateDialog} onOpenChange={setShowGenerateDialog}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              {selectedTemplateData?.icon}
              Generate {selectedTemplateData?.name}
            </DialogTitle>
            <DialogDescription>
              {selectedTemplateData?.description}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label htmlFor="reportName">Report Name *</Label>
              <Input
                id="reportName"
                value={reportParameters.name}
                onChange={(e) =>
                  setReportParameters({
                    ...reportParameters,
                    name: e.target.value,
                  })
                }
                placeholder="Enter report name"
                required
                maxLength={100}
              />
            </div>

            {selectedTemplateData?.fields.includes("dateRange") && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="dateFrom">From Date</Label>
                  <Input
                    id="dateFrom"
                    type="date"
                    value={reportParameters.dateFrom}
                    onChange={(e) =>
                      setReportParameters({
                        ...reportParameters,
                        dateFrom: e.target.value,
                      })
                    }
                  />
                </div>
                <div>
                  <Label htmlFor="dateTo">To Date</Label>
                  <Input
                    id="dateTo"
                    type="date"
                    value={reportParameters.dateTo}
                    onChange={(e) =>
                      setReportParameters({
                        ...reportParameters,
                        dateTo: e.target.value,
                      })
                    }
                  />
                </div>
              </div>
            )}

            {selectedTemplateData?.fields.includes("projects") && (
              <div>
                <Label>Projects (Select multiple)</Label>
                <div className="grid grid-cols-2 gap-2 mt-2">
                  {projects.map((project) => (
                    <div
                      key={project.id}
                      className="flex items-center space-x-2"
                    >
                      <Checkbox
                        id={project.id}
                        checked={reportParameters.projects.includes(
                          project.name,
                        )}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setReportParameters({
                              ...reportParameters,
                              projects: [
                                ...reportParameters.projects,
                                project.name,
                              ],
                            });
                          } else {
                            setReportParameters({
                              ...reportParameters,
                              projects: reportParameters.projects.filter(
                                (p) => p !== project.name,
                              ),
                            });
                          }
                        }}
                      />
                      <Label htmlFor={project.id} className="text-sm">
                        {project.name}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {selectedTemplateData?.fields.includes("donors") && (
              <div>
                <Label>Donors (Select multiple)</Label>
                <div className="grid grid-cols-2 gap-2 mt-2">
                  {donors.map((donor) => (
                    <div key={donor.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={donor.id}
                        checked={reportParameters.donors.includes(donor.name)}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setReportParameters({
                              ...reportParameters,
                              donors: [...reportParameters.donors, donor.name],
                            });
                          } else {
                            setReportParameters({
                              ...reportParameters,
                              donors: reportParameters.donors.filter(
                                (d) => d !== donor.name,
                              ),
                            });
                          }
                        }}
                      />
                      <Label htmlFor={donor.id} className="text-sm">
                        {donor.name}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {selectedTemplateData?.fields.includes("categories") && (
              <div>
                <Label>Expense Categories (Select multiple)</Label>
                <div className="grid grid-cols-2 gap-2 mt-2">
                  {categories.map((category) => (
                    <div
                      key={category.id}
                      className="flex items-center space-x-2"
                    >
                      <Checkbox
                        id={category.id}
                        checked={reportParameters.categories.includes(
                          category.name,
                        )}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setReportParameters({
                              ...reportParameters,
                              categories: [
                                ...reportParameters.categories,
                                category.name,
                              ],
                            });
                          } else {
                            setReportParameters({
                              ...reportParameters,
                              categories: reportParameters.categories.filter(
                                (c) => c !== category.name,
                              ),
                            });
                          }
                        }}
                      />
                      <Label htmlFor={category.id} className="text-sm">
                        {category.name}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="grid grid-cols-2 gap-4">
              {selectedTemplateData?.fields.includes("includeCharts") && (
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="includeCharts"
                    checked={reportParameters.includeCharts}
                    onCheckedChange={(checked) =>
                      setReportParameters({
                        ...reportParameters,
                        includeCharts: !!checked,
                      })
                    }
                  />
                  <Label htmlFor="includeCharts">Include Charts & Graphs</Label>
                </div>
              )}

              {selectedTemplateData?.fields.includes("includeDetails") && (
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="includeDetails"
                    checked={reportParameters.includeDetails}
                    onCheckedChange={(checked) =>
                      setReportParameters({
                        ...reportParameters,
                        includeDetails: !!checked,
                      })
                    }
                  />
                  <Label htmlFor="includeDetails">
                    Include Detailed Breakdown
                  </Label>
                </div>
              )}
            </div>

            <div>
              <Label htmlFor="format">Export Format</Label>
              <Select
                value={reportParameters.format}
                onValueChange={(value) =>
                  setReportParameters({ ...reportParameters, format: value })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="pdf">PDF (Recommended)</SelectItem>
                  <SelectItem value="csv">CSV</SelectItem>
                  <SelectItem value="excel">Excel</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex justify-end gap-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => setShowGenerateDialog(false)}
              >
                Cancel
              </Button>
              <Button
                onClick={handleGenerateReport}
                disabled={!reportParameters.name || generating}
              >
                {generating ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    Generating...
                  </>
                ) : (
                  "Generate Report"
                )}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Generated Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Generated Reports</CardTitle>
          <CardDescription>
            Previously generated reports and their current status
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>File Size</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      {getTypeIcon(report.type)}
                      <div>
                        <div className="font-medium">{report.name}</div>
                        <div className="text-sm text-gray-500">
                          {report.description}
                        </div>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">
                      {report.type.replace("_", " ").toUpperCase()}
                    </Badge>
                  </TableCell>
                  <TableCell>{report.generated_by}</TableCell>
                  <TableCell>
                    {new Date(report.generated_at).toLocaleDateString()}
                  </TableCell>
                  <TableCell>
                    <Badge className={getStatusColor(report.status)}>
                      {report.status.toUpperCase()}
                    </Badge>
                  </TableCell>
                  <TableCell>{report.file_size || "~1.2 MB"}</TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      {report.status === "generated" && (
                        <>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handlePreviewReport(report)}
                            title="Preview Report"
                          >
                            <Eye className="h-3 w-3" />
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleDownloadReport(report)}
                            title="Download Report"
                          >
                            <Download className="h-3 w-3" />
                          </Button>
                        </>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {reports.length === 0 && (
            <div className="text-center py-8 text-gray-500">
              No reports generated yet. Create your first report using the
              templates above.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
